### ISSUE TITLE
Running through the setup wizard multiple times produces the wrong config file

### ISSUE THREAD

**Issue by Jille** [Jille/rufs#60]
Should be easy to prevent at config rewriting time. Just replace the existing circle with a new empty one. For shares just replace the old share with that name with the new one?

```
circles:
- name: rufs.hashru.nl
  shares:
  - local: C:\talks
    remote: talks
  - local: C:\recordings
    remote: recordings
  - local: C:\talks
    remote: talks
  - local: C:\recordings
    remote: recordings
  - local: C:\recordings
    remote: recordings
  - local: C:\talks
    remote: talks
  - local: C:\recordings
    remote: recordings
- name: rufs.hashru.nl
  shares: []
- name: rufs.hashru.nl
  shares: []
- name: rufs.hashru.nl
  shares: []
- name: rufs.hashru.nl
  shares: []
- name: rufs.hashru.nl
  shares: []
- name: rufs.hashru.nl
  shares: []
- name: rufs.hashru.nl
  shares: []
mountpoint: "R:"
```
